# Generated by Django 3.2.5 on 2021-07-10 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChessGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=8, unique=True)),
                ('host', models.CharField(max_length=50, unique=True)),
                ('guest', models.CharField(max_length=50, unique=True)),
                ('max_time', models.IntegerField()),
                ('host_curr_time', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('guest_curr_time', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chess_annotations', models.TextField(default='', max_length=1000)),
            ],
        ),
    ]
