# Generated by Django 3.2.5 on 2021-07-11 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chessgame',
            name='guest',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
