# Generated by Django 3.2.5 on 2021-07-13 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_codes_chessgame_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='chessgame',
            name='fen',
            field=models.TextField(default='start', max_length=50),
        ),
    ]
