# Generated by Django 3.2.5 on 2021-07-14 03:35

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_chessgame_fen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chessgame',
            name='code',
            field=models.CharField(default=api.models.generate_unique_code, max_length=8),
        ),
    ]
